### ISSUE TITLE
Darp6/galp4 loss of back light control

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/system76-acpi-dkms#15]
**Distribution (run `cat /etc/os-release`):**
Pop!OS 20.04/21.04/21.10 and Ubuntu 20.04 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76-acpi-dkms:
  Installed: 1.0.2~1635519829~21.10~b49caa5
```
**Issue/Bug Description:**
On darp6/galp4 back light control is lost after [PR to fix booting](https://github.com/pop-os/system76-acpi-dkms/pull/13)

**Steps to reproduce (if you know):**
Have darp6/galp4

**Expected behavior:**
Black light control to work from keyboard hotkeys.

**Other Notes:**
Related to updates that fixed booting.

**Comment by jacobgkau** [comment]
This issue only affects proprietary EC and does not affect Open EC; darp6 users should transition to Open EC if possible. galp4 does not have Open EC released, however.

**Comment by w4kus** [comment]
darp6 user here. How does one transition to Open EC..if possible?  I fixed this issue a by simply removing the call to get the "NFAN" and "NTMP" objects.

**Comment by thomas-zimmerman** [comment]
For darp6 users, you should be able to transition to the Open EC with the following commands:
```
sudo apt update && sudo apt install system76-firmware
sudo system76-firmware-cli schedule --open
```
This assumes that you are running Pop!OS or Ubuntu with the System76 PPA enabled.

**Comment by w4kus** [comment]
Thanks. I love my darp6  Hate it with things don't work

**Comment by smugcloud** [comment]
> For darp6 users, you should be able to transition to the Open EC with the following commands:
> 
> ```
> sudo apt update && sudo apt install system76-firmware
> sudo system76-firmware-cli schedule --open
> ```
> 
> This assumes that you are running Pop!OS or Ubuntu with the System76 PPA enabled.

Thanks for the pointer @thomas-zimmerman.  I have a darp6 impacted by this issue, and transitioning to the Open EC (per your commands), has not resolved this issue.  Has the Open EC fix been released @jacobgkau?

**Comment by jacobgkau** [comment]
@smugcloud Yes, Open EC was released for darp6 in September 2020. Can you please provide the output of `sudo dmidecode` in a text file to confirm your current version?

**Comment by smugcloud** [comment]
Thanks @jacobgkau.  Of course, as soon as I wake my machine, the back light is working (when it was not after the firmware install).

Here is the output regardless.  Thanks for the help!
[backlight.txt](https://github.com/pop-os/system76-acpi-dkms/files/7757370/backlight.txt)

**Comment by jacobgkau** [comment]
> Thanks @jacobgkau. Of course, as soon as I wake my machine, the back light is working (when it was not after the firmware install).
> 
> Here is the output regardless. Thanks for the help! [backlight.txt](https://github.com/pop-os/system76-acpi-dkms/files/7757370/backlight.txt)

`2021-07-20_93c2809` is the correct version for Open EC. Glad to hear it's working.
